/**
 * Types mirroring the backend's Pydantic request/response models.
 * Keep this file in lockstep with this project's API contract and the
 * backend's `models.py` once that lands.
 */

export type FailureReason =
  | "insufficient_funds"
  | "bank_timeout"
  | "network_error"
  | "card_expired"
  | "fraud_block"
  | "other";

export type TransactionType = "one_time" | "subscription";

export type PreferredChannel = "sms" | "whatsapp" | "email" | "voice" | "none";

export type InterventionId =
  | "no_action"
  | "retry_now"
  | "retry_later"
  | "sms_link"
  | "whatsapp_nudge"
  | "email"
  | "voice_call";

export interface Customer {
  customer_id: string;
  ltv: number;
  past_success_rate: number;
  preferred_channel: PreferredChannel;
}

export interface FailedPayment {
  payment_id: string;
  customer_id: string;
  amount: number;
  failure_reason: FailureReason;
  transaction_type: TransactionType;
  failed_at: string; // ISO datetime
  retry_count_so_far: number;
}

/** One line item in the "all interventions considered" breakdown for a decision. */
export interface InterventionEvaluation {
  intervention_id: InterventionId;
  probability_recovery: number; // P(recovery | context, intervention), 0-1
  amount: number;
  unit_cost: number;
  expected_value: number; // P(recovery) * amount - unit_cost
  status: "chosen" | "rejected" | "blocked_by_guardrail";
  /** Present when status is "rejected" or "blocked_by_guardrail", the human-readable reason it lost. */
  rejection_reason?: string;
}

export interface Decision {
  decision_id: string;
  payment_id: string;
  customer_id: string;
  amount: number;
  failure_reason: FailureReason;
  transaction_type: TransactionType;
  /** How many times this payment had already been retried before this decision. */
  retry_count_so_far: number;
  chosen_intervention: InterventionId;
  decided_at: string; // ISO datetime
  /** Every intervention the optimizer considered, including the winner and all rejected/blocked alternatives. */
  evaluations: InterventionEvaluation[];
  /** Short ops-readable rationale generated by the LLM explanation step, grounded in the evaluation fields. */
  explanation: string;
  /** Real Razorpay test-mode payment link, only present when chosen_intervention is "sms_link" and the live API call succeeded. */
  payment_link_url?: string | null;
  /** Set when a payment link was expected (sms_link chosen) but the live call didn't produce one -- missing keys or an API failure. */
  payment_link_error?: string | null;
}

export interface SimulateRequest {
  n_customers?: number;
  n_training_logs?: number;
  n_batch_payments?: number;
  seed?: number;
}

export interface SimulateResponse {
  batch_id: string;
  n_customers: number;
  n_failed_payments: number;
  generated_at: string;
}

export interface DecideResponse {
  decision: Decision;
}

export interface DecisionsListResponse {
  items: Decision[];
  total: number;
  page: number;
  page_size: number;
}

export interface PolicyResult {
  policy_id: "always_do_nothing" | "always_retry_now" | "rule_based_heuristic" | "ev_optimized";
  policy_label: string;
  total_expected_revenue_recovered: number;
  total_intervention_cost: number;
  net_revenue: number;
  net_revenue_per_rupee: number;
}

export interface EvaluateResponse {
  evaluated_at: string;
  batch_size: number;
  policies: PolicyResult[];
}

export interface CalibrationPoint {
  bucket_start: number;
  bucket_end: number;
  predicted_mean: number;
  observed_mean: number;
  n: number;
}

export interface MetricsResponse {
  auc: number;
  brier_score: number;
  calibration_curve: CalibrationPoint[];
  trained_at: string;
  n_training_rows: number;
}

// ---------------------------------------------------------------------------
// Payment Success Score (v2, see docs/PAYMENT_PAGE.md) -- pre-failure
// prediction, an entirely separate pipeline from the RVE decision flow
// above. Offline/synthetic, same as the rest of this app; never executes
// anything real. See docs/PAYMENT_PAGE.md for the full honesty boundary.
// ---------------------------------------------------------------------------

export type PaymentMethod = "upi" | "card" | "netbanking" | "wallet";

export interface PSSConditions {
  gateway_latency_ms: number;
  gateway_error_rate: number;
  traffic_load_index: number;
  merchant_uptime_pct: number;
  amount: number;
  transaction_type: TransactionType;
}

export interface PSSMethodScore {
  method: PaymentMethod;
  success_probability: number;
  score: number; // 0-100
  recommended: boolean;
}

export interface PSSScoreResponse {
  conditions: PSSConditions;
  methods: PSSMethodScore[]; // sorted descending by success_probability
  recommended_method: PaymentMethod;
  healthy_baseline_score: number;
  delta_from_healthy: number;
}

// ---------------------------------------------------------------------------
// Recovery Lab -- "Revenue Recovery Digital Twin". Offline/synthetic
// merchant-strategy simulation built on top of the RVE decision pipeline
// above. Field names mirror backend/app/models.py's RecoveryLab* Pydantic
// models directly (built together, unlike the RVE/PSS types above which
// independently drifted and needed api/adapt.ts to reconcile) -- no adapter
// needed here.
// ---------------------------------------------------------------------------

export type RecoveryLabPolicyId = "no_intervention" | "always_retry" | "aggressive_recovery" | "rve_adaptive";

export type ContactIntensity = "low" | "moderate" | "high";

export interface RecoveryLabExposureResponse {
  total_at_risk: number;
  n_failed_payments: number;
  median_payment_value: number;
  suggested_policy_label: string;
  note: string;
}

export interface RecoveryLabSimulateRequest {
  policy: RecoveryLabPolicyId;
  contact_intensity: ContactIntensity;
  discount_budget: number;
  voice_capacity: number;
  max_contacts_per_customer: number;
  recovery_window_hours: number;
  n_simulation_runs: number;
  seed: number;
}

export interface RecoveryLabPolicyMetrics {
  policy_id: RecoveryLabPolicyId;
  policy_label: string;
  n_payments_in_scope: number;
  total_at_risk: number;
  natural_recovery: number;
  gross_recovery: number;
  incremental_recovery: number;
  intervention_cost: number;
  net_value_created: number;
  recovery_rate: number;
  incremental_recovery_rate: number;
  number_intervened: number;
  number_contacted: number;
  number_blocked_by_guardrail: number;
  number_blocked_by_capacity: number;
  number_blocked: number;
  average_cost_per_recovery: number;
  net_value_low: number | null;
  net_value_high: number | null;
}

export interface RecoveryLabSimulateResponse {
  seed: number;
  n_simulation_runs: number;
  primary_policy_id: RecoveryLabPolicyId;
  n_payments_in_scope: number;
  total_at_risk: number;
  policies: RecoveryLabPolicyMetrics[]; // always all four, fixed order
  insight: string;
  example_payment_id: string | null;
  note: string;
}

export interface RecoveryLabSensitivityRequest {
  policy: RecoveryLabPolicyId;
  dimension: "voice_capacity" | "discount_budget" | "max_contacts_per_customer";
  contact_intensity: ContactIntensity;
  discount_budget: number;
  voice_capacity: number;
  max_contacts_per_customer: number;
  recovery_window_hours: number;
  seed: number;
  levels?: number[];
}

export interface RecoveryLabSensitivityPoint {
  level: number;
  incremental_recovery: number;
  intervention_cost: number;
  net_value_created: number;
}

export interface RecoveryLabSensitivityResponse {
  dimension: string;
  policy_id: RecoveryLabPolicyId;
  points: RecoveryLabSensitivityPoint[];
  optimal_level: number;
  optimal_net_value: number;
  insight: string;
  note: string;
}

// ---------------------------------------------------------------------------
// Revenue Recovery Autopsy. A forensic root-cause layer built on top of the
// existing synthetic batch and the existing RVE audit log -- see
// docs/REVENUE_RECOVERY_AUTOPSY.md. Field names mirror backend/app/models.py's
// Revenue*/ForensicPaymentRecord/RootCauseDetail/FixFirstOpportunity models
// directly, no adapter needed (same convention as Recovery Lab's types).
// ---------------------------------------------------------------------------

export type RootCauseCategory = "payment_infrastructure" | "customer" | "checkout" | "recovery" | "policy" | "unknown_multi_factor";

export type RevenueOutcome = "natural_recovery" | "intervention_recovery" | "recoverable" | "permanently_lost" | "unresolved";

export interface ContributingCause {
  cause_key: string;
  label: string;
  detail: string;
}

export interface ForensicPaymentRecord {
  payment_id: string;
  customer_id: string;
  amount: number;
  failure_reason: FailureReason;
  transaction_type: TransactionType;
  payment_method: string;
  gateway: string;
  checkout_started_at: string;
  payment_attempted_at: string;
  failed_at: string;
  recovery_decision_at: string | null;
  recovery_executed_at: string | null;
  recovered_at: string | null;
  chosen_intervention: InterventionId | null;
  probability_of_recovery: number | null;
  expected_value: number | null;
  recovered: boolean | null;
  outcome: RevenueOutcome;
  primary_cause_key: string;
  primary_cause_category: RootCauseCategory;
  primary_cause_label: string;
  contributing_causes: ContributingCause[];
  recovery_decision_delay_hours: number | null;
  time_to_recovery_hours: number | null;
  preventable_amount: number;
}

export interface RevenueLeakageSummary {
  total_at_risk: number;
  total_recovered: number;
  natural_recovery_amount: number;
  intervention_recovery_amount: number;
  revenue_lost: number;
  recoverable_amount: number;
  permanently_lost_amount: number;
  unresolved_amount: number;
  preventable_amount: number;
  n_payments: number;
  n_natural_recovery: number;
  n_intervention_recovery: number;
  n_recoverable: number;
  n_permanently_lost: number;
  n_unresolved: number;
  definitions: Record<string, string>;
}

export interface LossChainBreakdownItem {
  label: string;
  count: number;
  amount: number;
  percentage_of_total: number;
}

export interface LossChainStage {
  stage: string;
  label: string;
  count: number;
  amount: number;
  percentage_of_total: number;
  note: string | null;
  breakdown: LossChainBreakdownItem[];
}

export interface RecoveryDelayBucket {
  label: string;
  n_payments: number;
  n_recovered: number;
  recovery_rate: number;
}

export interface RecoveryDelayAnalysis {
  buckets: RecoveryDelayBucket[];
  mean_time_to_first_intervention_hours: number | null;
  mean_time_to_recovery_hours: number | null;
  disclaimer: string;
}

export interface ParetoResult {
  top_share_of_causes: number;
  revenue_share: number;
  concentration_detected: boolean;
  statement: string;
}

export interface RevenueAutopsySummaryResponse {
  leakage: RevenueLeakageSummary;
  loss_chain: LossChainStage[];
  recovery_delay: RecoveryDelayAnalysis;
  pareto: ParetoResult;
  note: string;
}

export interface RootCauseDetail {
  cause_key: string;
  category: RootCauseCategory;
  label: string;
  kind: "primary" | "contributing";
  n_payments: number;
  amount: number;
  percentage_of_total: number;
  recovery_rate: number;
  preventable_amount: number;
  preventability_factor: number;
  mean_recovery_delay_hours: number | null;
  top_intervention: InterventionId | null;
  note: string | null;
}

export interface FixFirstOpportunity {
  priority: number;
  cause_key: string;
  category: RootCauseCategory;
  label: string;
  revenue_affected: number;
  preventable_amount: number;
  feasibility: number;
  estimated_fix_cost: number;
  opportunity_score: number;
  expected_value_of_fix: number;
  why: string;
}

export interface RevenueAutopsyCausesResponse {
  causes: RootCauseDetail[];
  fix_first: FixFirstOpportunity[];
  top_recommendation: FixFirstOpportunity | null;
  formula_note: string;
  note: string;
}

export interface RevenueAutopsyPaymentsResponse {
  total: number;
  page: number;
  page_size: number;
  items: ForensicPaymentRecord[];
  note: string;
}

export interface RevenueAutopsyPaymentsParams {
  page?: number;
  page_size?: number;
  cause?: string;
  status?: string;
  search?: string;
}

// ---------------------------------------------------------------------------
// Recovery Negotiation Engine. A higher-level layer over the RVE decision
// above: RVE picks WHICH intervention; this searches HOW MUCH incentive
// (Rs.) is worth attaching to it. Field names mirror backend/app/models.py's
// Negotiation* Pydantic models directly, no adapter needed (same convention
// as Recovery Lab, PSS, and Revenue Autopsy).
// ---------------------------------------------------------------------------

export interface NegotiationAnalyzeRequest {
  payment_id: string;
  min_incentive?: number;
  max_incentive?: number;
  step?: number;
  optimization_tolerance?: number;
}

export interface NegotiationCandidate {
  incentive: number;
  eligible: boolean;
  blocked_reason: string | null;
  recovery_probability: number | null;
  incremental_recovery: number | null;
  incentive_cost: number | null;
  intervention_cost: number | null;
  expected_gross_recovery: number | null;
  expected_net_value: number | null;
}

export interface NegotiationAnalyzeResponse {
  payment_id: string;
  amount: number;
  failure_reason: FailureReason;
  customer_id: string;
  base_intervention: InterventionId;
  base_probability: number;
  base_expected_value: number;
  candidates: NegotiationCandidate[];
  max_recovery_probability_candidate: number | null;
  optimum_candidate: number | null;
  minimum_effective_intervention: number | null;
  optimization_tolerance: number;
  margin_protected: number | null;
  explanation: string;
  note: string;
}
