/**
 * Types mirroring the backend's Pydantic request/response models.
 * Keep this file in lockstep with the API contract in the repo's CLAUDE.md
 * (Section 13) and the backend's `models.py` once that lands.
 */

export type FailureReason =
  | "insufficient_funds"
  | "bank_timeout"
  | "network_error"
  | "card_expired"
  | "fraud_block"
  | "other";

export type TransactionType = "one_time" | "subscription";

export type PreferredChannel = "sms" | "whatsapp" | "email" | "voice" | "none";

export type InterventionId =
  | "no_action"
  | "retry_now"
  | "retry_later"
  | "sms_link"
  | "whatsapp_nudge"
  | "email"
  | "voice_call";

export interface Customer {
  customer_id: string;
  ltv: number;
  past_success_rate: number;
  preferred_channel: PreferredChannel;
}

export interface FailedPayment {
  payment_id: string;
  customer_id: string;
  amount: number;
  failure_reason: FailureReason;
  transaction_type: TransactionType;
  failed_at: string; // ISO datetime
  retry_count_so_far: number;
}

/** One line item in the "all interventions considered" breakdown for a decision. */
export interface InterventionEvaluation {
  intervention_id: InterventionId;
  probability_recovery: number; // P(recovery | context, intervention), 0-1
  amount: number;
  unit_cost: number;
  expected_value: number; // P(recovery) * amount - unit_cost
  status: "chosen" | "rejected" | "blocked_by_guardrail";
  /** Present when status is "rejected" or "blocked_by_guardrail", the human-readable reason it lost. */
  rejection_reason?: string;
}

export interface Decision {
  decision_id: string;
  payment_id: string;
  customer_id: string;
  amount: number;
  failure_reason: FailureReason;
  transaction_type: TransactionType;
  chosen_intervention: InterventionId;
  decided_at: string; // ISO datetime
  /** Every intervention the optimizer considered, including the winner and all rejected/blocked alternatives. */
  evaluations: InterventionEvaluation[];
  /** Short ops-readable rationale generated by the LLM explanation step, grounded in the evaluation fields. */
  explanation: string;
  /** Real Razorpay test-mode payment link, only present when chosen_intervention is "sms_link" and the live API call succeeded. */
  payment_link_url?: string | null;
  /** Set when a payment link was expected (sms_link chosen) but the live call didn't produce one -- missing keys or an API failure. */
  payment_link_error?: string | null;
}

export interface SimulateRequest {
  n_customers?: number;
  n_training_logs?: number;
  n_batch_payments?: number;
  seed?: number;
}

export interface SimulateResponse {
  batch_id: string;
  n_customers: number;
  n_failed_payments: number;
  generated_at: string;
}

export interface DecideResponse {
  decision: Decision;
}

export interface DecisionsListResponse {
  items: Decision[];
  total: number;
  page: number;
  page_size: number;
}

export interface PolicyResult {
  policy_id: "always_do_nothing" | "always_retry_now" | "rule_based_heuristic" | "ev_optimized";
  policy_label: string;
  total_expected_revenue_recovered: number;
  total_intervention_cost: number;
  net_revenue: number;
  net_revenue_per_rupee: number;
}

export interface EvaluateResponse {
  evaluated_at: string;
  batch_size: number;
  policies: PolicyResult[];
}

export interface CalibrationPoint {
  bucket_start: number;
  bucket_end: number;
  predicted_mean: number;
  observed_mean: number;
  n: number;
}

export interface MetricsResponse {
  auc: number;
  brier_score: number;
  calibration_curve: CalibrationPoint[];
  trained_at: string;
  n_training_rows: number;
}

// ---------------------------------------------------------------------------
// Payment Success Score (v2, see CLAUDE.md Section 20) -- pre-failure
// prediction, an entirely separate pipeline from the RVE decision flow
// above. Offline/synthetic, same as the rest of this app; never executes
// anything real. See CLAUDE.md Section 20 for the full honesty boundary.
// ---------------------------------------------------------------------------

export type PaymentMethod = "upi" | "card" | "netbanking" | "wallet";

export interface PSSConditions {
  gateway_latency_ms: number;
  gateway_error_rate: number;
  traffic_load_index: number;
  merchant_uptime_pct: number;
  amount: number;
  transaction_type: TransactionType;
}

export interface PSSMethodScore {
  method: PaymentMethod;
  success_probability: number;
  score: number; // 0-100
  recommended: boolean;
}

export interface PSSScoreResponse {
  conditions: PSSConditions;
  methods: PSSMethodScore[]; // sorted descending by success_probability
  recommended_method: PaymentMethod;
  healthy_baseline_score: number;
  delta_from_healthy: number;
}
